wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.12.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1649158092
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      4: 3.9.7
      5: 0.12.9
      6: 4.12.2
      8:
      - 1
      - 3
      - 5
